apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: task_app_deployment
spec:  #under specs comes template of pods you want replicaSet to run, skip apiVersion and kind from pod_creation.yml file
  template:
    metadata:
      labels:
        app: task_app_db
    spec:
      containers:
      - name: Postgres_db_container
        image: postgres:15-alpine
  replicas: 1
  selector: 
    matchLabels:
      app: task_app_db 