apiVersion: v1
kind: Service
metadata:
  name: db_service
spec:  #can contain multiple containers
  type: ClusterIP     #clusterip is default. other Types: NodePort
  ports:
  - targetPort: 5432  #targetport is where backend/frontend is listening to. this is the port where frontend communicates with backend stuff like that
    port: 5432        #port is where service is exposed. this is the port we access through web and stuff

  selector:
    app: task_app_db