apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend_deployment
  labels:
    app: task_app_deployment
spec:  #under specs comes template of pods you want replicaSet to run, skip apiVersion and kind from pod_creation.yml file
  template:
    metadata:
      labels:
        app: task_app_frontend
    spec:
      containers:
      - name: frontend_container
        image: 058835008914.dkr.ecr.ap-south-1.amazonaws.com/frontend_repo:latest
  replicas: 1
  selector: 
    matchLabels:
      app: task_app_frontend 